 trigger:
 - master

 pool:
   vmImage: 'mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim' 

 variables:
   imageName: 'Listjj-image'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: ./Dockerfile