 trigger:
 - master

 pool:
   vmImage: 'ubuntu-latest' 

 variables:
   imageName: 'jarekj9/listjj_blazor_api'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: ./Dockerfile