 trigger:
 - master

 pool:
   vmImage: 'ubuntu-latest' 

 variables:
   imageName: 'jarekj9/listjj_blazor_api'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: ./Dockerfile
     tags: |
       latest

 - task: Docker@2
   inputs:
    containerRegistry: 'dockerhub'
    repository: 'jarekj9/listjj_blazor_api'
    command: 'push'
    tags: |
      latest