# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'jarekj9/listjj_blazor_api'
  CONTAINER_NAME: 'listjj_blazor_ap'
  ZAP_CONTAINER_NAME: 'owasp-zap'
  TEST_URL: 'http://localhost:5000' 

stages:

- stage: TestSecurity
  jobs:
  - job: SecurityScan
    steps:
    - script: |
        docker network create zap-net
        docker run -d --rm --name $(CONTAINER_NAME) --network zap-net -p 5000:5000 $(IMAGE_NAME)
        docker run -d --rm --name $(ZAP_CONTAINER_NAME) --network zap-net owasp/zap2docker-stable
        sleep 10  # Give time for services to start
      displayName: 'Start .NET App and OWASP ZAP'

    - script: |
        docker exec $(ZAP_CONTAINER_NAME) zap-baseline.py -t $(TEST_URL) -r zap_report.html || true
      displayName: 'Run OWASP ZAP Scan'

    - script: |
        docker cp $(ZAP_CONTAINER_NAME):/zap/zap_report.html $(Build.ArtifactStagingDirectory)/zap_report.html
      displayName: 'Copy ZAP Report'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/zap_report.html'
        artifactName: 'ZAPReport'
      displayName: 'Publish ZAP Report'

    - script: |
        docker stop $(CONTAINER_NAME)
        docker stop $(ZAP_CONTAINER_NAME)
        docker network rm zap-net
      displayName: 'Clean Up'