FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETARCH
WORKDIR /src
COPY Listjj/Listjj.csproj .
RUN dotnet restore "Listjj.csproj" -a $TARGETARCH
COPY . .
WORKDIR /src/Listjj/
RUN dotnet build "Listjj.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Listjj.csproj" -a $TARGETARCH -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV ASPNETCORE_HTTP_PORTS=80
ENV ASPNETCORE_URLS=http://*:80

ENTRYPOINT ["dotnet", "Listjj.dll"]
