FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim AS build
WORKDIR /src
COPY ListjjFrontEnd/ListjjFrontEnd.csproj .
RUN dotnet restore ListjjFrontEnd.csproj
COPY . .
WORKDIR /src/ListjjFrontEnd/
RUN dotnet build ListjjFrontEnd.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish ListjjFrontEnd.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY frontend_nginx.conf /etc/nginx/nginx.conf


