trigger:
- none
pr:
- none

pool:
  vmImage: ubuntu-latest

variables:
  SONARQUBE_IMAGE: 'sonarqube:lts-community'
  SONARQUBE_CONTAINERNAME: 'sonarqube'
  POSTGRES_IMAGE: 'postgres:13'
  POSTGRES_CONTAINERNAME: 'sonar_db'

steps:
- script: |
    docker network create common-net
    docker run --rm -d --name $(POSTGRES_CONTAINERNAME) --network common-net \
     -e POSTGRES_USER=sonar \
     -e POSTGRES_PASSWORD=sonar \
     -e POSTGRES_DB=sonar \
     $(POSTGRES_IMAGE)
  displayName: 'Run PostgreSQL DB container'

- script: |
    docker run --rm -d --name $(SONARQUBE_CONTAINERNAME) --network common-net \
     -e SONAR_JDBC_URL=jdbc:postgresql://$(POSTGRES_CONTAINERNAME):5432/sonar \
     -e SONAR_JDBC_USERNAME=sonar \
     -e SONAR_JDBC_PASSWORD=sonar \
     -p 9009:9000 \
     $(SONARQUBE_IMAGE)
  displayName: 'Run SonarQube container'

- script: sleep 60;docker ps

- script: |
    TOKEN=$(curl -u admin:admin -X POST "http://localhost:9009/api/user_tokens/generate" -d "name=myToken" | grep -o '"token":"[^"]*' | sed 's/"token":"//')
    echo $TOKEN
    ls $(Build.SourcesDirectory)
    docker run \
      --rm \
      -v $(Build.SourcesDirectory):/usr/src \
      --network common-net \
      -e SONAR_HOST_URL="http://sonarqube:9000" \
      -e SONAR_TOKEN=$TOKEN \
      sonarsource/sonar-scanner-cli:latest \
      sonar-scanner -Dsonar.projectKey=my_project
  displayName: 'Run SonarQube scan'

- script: |
    curl -u "$TOKEN" \
     -o report.json \
     "http://localhost:9009/api/issues/search?componentKeys=my_project"
  displayName: 'Get scan report'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)/report.json
    artifactName: SonarQubeReport
  displayName: "Publish SonarQube Report"

- script: |
    docker stop $(SONARQUBE_CONTAINERNAME)
    docker stop $(POSTGRES_CONTAINERNAME)
    docker network rm common-net
  displayName: 'Clean Up'