trigger:
- master # or the name of your main branch

steps:
# Prepare Analysis Configuration task
- checkout: self
  fetchDepth: 0
- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'j-jan SonarQube Cloud'
    organization: 'j-jan'
    scannerMode: 'dotnet'
    dotnetScannerVersion: '8.0.3.99785'
    projectKey: 'j-jan_Listjj_blazor'
    projectName: 'Listjj_blazor'
- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'