trigger: none
pr: none

#trigger:
#  - master

pool:
  vmImage: 'ubuntu-latest' 

variables:
  apiImageName: 'jarekj9/listjj_blazor_api'
  frontendBlazorImageName: 'jarekj9/listjj_frontend_blazor'

steps:

- task: CmdLine@2
  displayName: 'Install emulator for arm building'
  inputs:
    script: |
      sudo rm -f /etc/apt/apt-mirrors.txt
      sudo apt-get update
      sudo apt-get install -y qemu-system qemu-user-static

- task: Docker@2
  displayName: Build api image
  inputs:
    repository: $(apiImageName)
    command: build
    arguments: '--platform linux/arm64'
    Dockerfile: ./Dockerfile_multiarch
    tags: |
      arm

- task: Docker@2
  displayName: Push api image
  inputs:
   containerRegistry: 'dockerhub'
   repository: $(apiImageName)
   command: 'push'
   tags: |
     arm

- task: Docker@2
  displayName: Build blazor frontend image
  inputs:
    repository: $(frontendBlazorImageName)
    command: build
    arguments: '--platform linux/arm64'
    Dockerfile: ./Dockerfile_frontend_multiarch
    tags: |
      arm

- task: Docker@2
  displayName: Push blazor frontend image
  inputs:
   containerRegistry: 'dockerhub'
   repository: $(frontendBlazorImageName)
   command: 'push'
   tags: |
     arm
