# trigger: none
# pr: none
trigger:
 tags:
  include:
   - '*'
 branches:
  include:
   - none
 batch: true


pool:
  vmImage: 'ubuntu-22.04'

variables:
  apiImageName: 'jarekj9/listjj_blazor_api'
  frontendBlazorImageName: 'jarekj9/listjj_frontend_blazor'

steps:

- task: CmdLine@2
  displayName: 'Install emulator for arm building'
  inputs:
    script: |
      sudo apt-get update
      sudo apt-get install -y qemu-user-static binfmt-support

- script: |
    VERSION="${BUILD_SOURCEBRANCH#refs/tags/}"
    echo "Tag detected: $VERSION"
    sed -i "s/^[[:space:]]*\"Version\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"Version\": \"${VERSION}\",/" ./Listjj/appsettings.json 
    grep -n "Version" ./Listjj/appsettings.json
  displayName: "Update version in appsettings.json"

- task: Docker@2
  displayName: Build api image
  inputs:
    repository: $(apiImageName)
    command: build
    arguments: '--platform linux/arm64'
    Dockerfile: ./Dockerfile_multiarch
    tags: |
      latest

- task: Docker@2
  displayName: Push api image
  inputs:
   containerRegistry: 'dockerhub'
   repository: $(apiImageName)
   command: 'push'
   tags: |
     latest

- task: Docker@2
  displayName: Build blazor frontend image
  inputs:
    repository: $(frontendBlazorImageName)
    command: build
    arguments: '--platform linux/arm64'
    Dockerfile: ./Dockerfile_frontend_multiarch
    tags: |
      latest

- task: Docker@2
  displayName: Push blazor frontend image
  inputs:
   containerRegistry: 'dockerhub'
   repository: $(frontendBlazorImageName)
   command: 'push'
   tags: |
     latest
