trigger:
- master

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  azureServiceConnection: 'j-jan-listjj-blazor-service-connection'
  resourceGroup: 'RGJJ-listjj'
  location: 'westeurope'
  subscriptionId: 'c5097964-89eb-42c7-9626-accc9e7a3515'

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/listjj-api-webapp-docker.bicep'
        deploymentMode: 'Incremental'
        overrideParameters: |
          appName='listjj-api'
          location='$(location)'
          mssqlConnString='$(mssqlConnString)'
