trigger:
- master

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  azureServiceConnection: 'j-jan-listjj-blazor-service-connection'
  resourceGroup: 'RGJJ-listjj'
  location: 'westeurope'
  subscriptionId: 'c5097964-89eb-42c7-9626-accc9e7a3515'
  blazorFrontAppName: 'listjj-blazor-front'
  apiEndpoint: "https://listjj-api.azurewebsites.net/"

stages:
- stage: Deploy
  jobs:
  - job: Deploy_Listjj_Api
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Listjj Api App Service using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/listjj-api-webapp-docker.bicep'
        overrideParameters: '-mssqlConnStringSecret "$(mssqlConnString)" -googleAuthClientSecret "$(googleAuthClientSecret)"'
        deploymentMode: 'Incremental'

    # - task: AzureResourceManagerTemplateDeployment@3
    #   displayName: Deploy Blazor Front App Service using docker/Bicep
    #   inputs:
    #     deploymentScope: 'Resource Group'
    #     azureResourceManagerConnection: $(azureServiceConnection)
    #     subscriptionId: $(subscriptionId)
    #     action: 'Create Or Update Resource Group'
    #     resourceGroupName: '$(resourceGroup)'
    #     location: '$(location)'
    #     templateLocation: 'Linked artifact'
    #     csmFile: 'infra/listjj-blazorfront-webapp-docker.bicep'
    #     deploymentMode: 'Incremental'

  - job: Deploy_Listjj_Blazor_Front
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroup) \
            --template-file infra/listjj-blazorfront-webapp-docker.bicep \
            --parameters appName='$(blazorFrontAppName)' location='$(location)'
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - script: |
        #cd app
        sed -i "s|\"ApiEndpoint\":.*|\"ApiEndpoint\": \"$(apiEndpoint)\",|" ListjjFrontEnd/wwwroot/appsettings.Development.json
        dotnet publish -c Release -o $(System.DefaultWorkingDirectory)/publish
      displayName: 'Build Blazor App'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        appName: $(blazorFrontAppName)
        package: '$(System.DefaultWorkingDirectory)/publish'