trigger: none
pr: none

steps:
  # Prepare Analysis Configuration task
  - checkout: self
    fetchDepth: 0
  - task: SonarCloudPrepare@3
    inputs:
      SonarQube: 'j-jan SonarQube Cloud'
      organization: 'j-jan'
      scannerMode: 'dotnet'
      dotnetScannerVersion: '8.0.3.99785'
      projectKey: 'j-jan_Listjj_blazor'
      projectName: 'Listjj_blazor'
      extraProperties: |
        sonar.sources=Listjj
        sonar.exclusions=**/wwwroot/**,**/tests/**,**/*.md,**/*.json

  - script: dotnet restore Listjj/Listjj.csproj
    displayName: 'Restore Dependencies'

  - script: dotnet build --configuration Release Listjj/Listjj.csproj
    displayName: 'Build Solution'

  - task: SonarQubeAnalyze@7
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'