name: Docker Image CI



on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  #IMAGE_NAME: jarekj9/listjj:$(date +%s)
  IMAGE_NAME: jarekj9/listjj:latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ env.IMAGE_NAME }}
      
    - name: docker tag
      run: docker tag -u jarekj9 -p ${{ secrets.DOCKER_TOKEN }} docker.io

    - name: docker login
      run: docker login -u jarekj9 -p ${{ secrets.DOCKER_TOKEN }} docker.io
      
    - name: docker push
      run: docker push ${{ env.IMAGE_NAME }}
