name: Docker Image CI



on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  IMAGE_NAME: jarekj9/listjj:$(date +%s)

jobs:

  build:

    runs-on: [self-hosted, runner1]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t jarekj9/listjj:$(date +%s) -t jarekj9/listjj:latest

    - name: docker login
      run: docker login -u jarekj9 -p ${{ secrets.DOCKER_TOKEN }} docker.io
      
    - name: docker push
      run: docker push jarekj9/listjj:latest
